title: My awsome title
author: Dave
email: info@lpt
description: > # this means to ignore newlines until "baseurl:"
  Awsome description

# social links
twitter_lovepattayaimfo: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_davidsimpson-pixel:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
